### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by MichZipp** [Pangyk/Graph_AE#5]
Hi @Pangyk, 

Thank you for the great work and for proving the code here on Git Hub.

I installed all the required libraries (python 3.7, pytorch 1.12.1 with cuda 10.2).

I tried to run the `train_compression.py` with all default values and run into the following error:

`Traceback (most recent call last):
  File ".../Graph_AE/train_compression.py", line 57, in <module>
    main(args)
  File ".../Graph_AE/train_compression.py", line 38, in main
    train_cp(model, optimizer, device, train_set, test_set, num_epoch, arg.model_dir, arg.m)
  File ".../Graph_AE/g_utils/train_utils.py", line 32, in train_cp
    z, _, _, _ = model(data)
  File ".../anaconda3/envs/graph_ae/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../Graph_AE/classification/Graph_AE.py", line 63, in forward
    f, attn = self.down_list[i](f, e, self.direction)
  File ".../anaconda3/envs/graph_ae/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File ".../Graph_AE/graph_ae/Layer.py", line 61, in forward
    pooling_result = g_pooling(attention_list, e_batch)
  File ".../anaconda3/envs/graph_ae/lib/python3.7/site-packages/torch_geometric/nn/pool/glob.py", line 31, in global_add_pool
    return scatter(x, batch, dim=-2, dim_size=size, reduce='add')
  File ".../anaconda3/envs/graph_ae/lib/python3.7/site-packages/torch_scatter/scatter.py", line 152, in scatter
    return scatter_sum(src, index, dim, out, dim_size)
  File ".../anaconda3/envs/graph_ae/lib/python3.7/site-packages/torch_scatter/scatter.py", line 15, in scatter_sum
    size[dim] = dim_size
IndexError: list assignment index out of range`

I tried to debug it but I couldn't resolve the issue.

The errors occur when calling `pooling_result = g_pooling(attention_list, e_batch)`  in `Layer.py`.

Do you have any suggestions?

Cheers,
Michael

**Comment by dandarm** [comment]
Hello @MichZipp ,
if still is of interest, I faced the same error and think a good workaround is
`attention_list.unsqueeze(1)` in file Layer.py

**Comment by MichZipp** [comment]
Hi @dandarm,

That fixed the issue. Thank you soo much for the workaround!

Cheers,
Michael
